"""add user xp, words, user_word_progress

Revision ID: 19e6f4f1e5a0
Revises: f7fd032be2a3
Create Date: 2026-07-09 17:21:07.668225
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e6f4f1e5a0'
down_revision: Union[str, None] = 'f7fd032be2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('term', sa.String(length=80), nullable=False),
    sa.Column('pos', sa.String(length=20), nullable=False),
    sa.Column('definition', sa.String(length=400), nullable=False),
    sa.Column('translation', sa.String(length=120), nullable=False),
    sa.Column('example', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_term'), 'words', ['term'], unique=True)
    op.create_table('user_word_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('word_id', sa.Uuid(), nullable=False),
    sa.Column('box', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word')
    )
    op.create_index(op.f('ix_user_word_progress_due_at'), 'user_word_progress', ['due_at'], unique=False)
    op.create_index(op.f('ix_user_word_progress_user_id'), 'user_word_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_word_progress_word_id'), 'user_word_progress', ['word_id'], unique=False)
    op.add_column('users', sa.Column('xp', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'xp')
    op.drop_index(op.f('ix_user_word_progress_word_id'), table_name='user_word_progress')
    op.drop_index(op.f('ix_user_word_progress_user_id'), table_name='user_word_progress')
    op.drop_index(op.f('ix_user_word_progress_due_at'), table_name='user_word_progress')
    op.drop_table('user_word_progress')
    op.drop_index(op.f('ix_words_term'), table_name='words')
    op.drop_table('words')
    # ### end Alembic commands ###
