"""add daily_study_aggregates

Revision ID: 72fc7ef3ae4c
Revises: 3269c6805646
Create Date: 2026-06-09 16:38:11.525640
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72fc7ef3ae4c'
down_revision: Union[str, None] = '3269c6805646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_study_aggregates',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_focus_seconds', sa.Integer(), nullable=False),
    sa.Column('sessions_count', sa.Integer(), nullable=False),
    sa.Column('completion_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_study_aggregates')
    # ### end Alembic commands ###
